<!doctype html>
<html>

<head>
<title>Лабораторна робота JavaScript. Гарбуз Тетяни.</title>
<meta charset="utf-8">
</head>

<body>
<div id="b1">
<div id="b2">
<img src="kartinka.jpeg" alt="логотип">      
<h1 onmouseover="document.getElementById('b3').	
borderStyle='2px solid lightred';" onmouseout="document.getElementById('b3').	
borderStyle='0px solid lightred';">Сайт Гарбуз Т. О. </h1>
<h3>Далеко не всегда ясно, в какие моменты жизни мы встречаемся с силой тока и моментом импульса.</h3>
</div>
<div id="b3">
<ul>
<li><a href="https://newtonew.com/book/bloomfild-physics/">Физика, с которой вы сталкиваетесь ежедневно</a></li>
<li><a href="https://rosuchebnik.ru/material/fizika-vokrug-nas-fizika-v-bytu-7355/">Физика вокруг нас. Физика в быту</a></li>
<li><a href="https://unium.ru/blog/do-i-really-need-physics/">Зачем учить физику в школе?</a></li>
</ul>

<ol>
<li>То есть мы уже и так знаем, что если бросить предмет, то он упадет на землю. Что это значит? 
<ul>
<li>Земля притягивает нас и все предметы.</li>
<li>Мало того, планета Земля притягивает даже</li>
<li>такой тяжелый космический предмет, как Луна.</li>
</ul>
</li>
<li>Заметим, что Луна не улетает по своей траектории </li>
<li> и каждый вечер показывается людям.</li>
</ol>

</div>
<div id="b4">
<p id="p1">Также не зависают в воздухе любые штуки,</p>
<p id="p2">которые мы в сердцах бросили на пол.</p>
<p id="p3">На брошенные предметы действует еще и ускорение,</p>
</div>
<div id="b5">
<table border="1">
<tr><td colspan="2">потому что у Земли огромная сила притяжения.</td></tr>
<tr><td>А также сила трения.</td><td>Поэтому, зная об этих законах, можно понять,</td></tr>
<tr><td>что происходит, если человек прыгает с парашютом.</td><td rowspan="3">Связана ли площадь парашюта</td></tr>
<tr><td>с замедлением скорости падения?</td></tr>
<tr><td>Может, стоит просить парашют побольше?</td></tr>
</table>
</div>
<div id="b6">&copy;Harbuz Tetyana &#169;Harbuz Tanya</div>
</div>
</body>

</html>
